import { Line } from '../../typings';

export const LONDON_LINES: Line[] = [
  {
    id: 'line-hammersmith-and-city',
    name: 'Hammersmith and City',
    stop: 'hammersmith-city',
    color: '#E58CA1',
    visible: true,
  },
  {
    id: 'line-circle',
    name: 'Circle',
    stop: 'circle',
    color: '#F8D448',
    visible: true,
  },
  {
    id: 'line-district',
    name: 'District',
    stop: 'district',
    color: '#3A8347',
    visible: true,
  },
  {
    id: 'line-metropolitan',
    name: 'Metropolitan',
    stop: 'metropolitan',
    color: '#8A195C',
    visible: true,
  },
  {
    id: 'line-central',
    name: 'Central',
    stop: 'central',
    color: '#DB4433',
    visible: true,
  },
  {
    id: 'line-piccadilly',
    name: 'Piccadilly',
    stop: 'piccadilly',
    color: '#253E8F',
    visible: true,
  },
  {
    id: 'line-northern',
    name: 'Northern',
    stop: 'northern',
    color: '#000000',
    visible: true,
  },
  {
    id: 'line-victoria',
    name: 'Victoria',
    stop: 'victoria',
    color: '#469BD7',
    visible: true,
  },
  {
    id: 'line-jubilee',
    name: 'Jubilee',
    stop: 'jubilee',
    color: '#969CA1',
    visible: true,
  },
  {
    id: 'line-bakerloo',
    name: 'Bakerloo',
    stop: 'bakerloo',
    color: '#A66527',
    visible: true,
  },
  // TODO: this is a duplication
  {
    id: 'line-waterloo',
    name: 'Waterloo',
    stop: 'waterloo',
    color: '#96CCBD',
    visible: true,
  },
  {
    id: 'line-elizabeth',
    name: 'Elizabeth',
    stop: 'elizabeth',
    color: '#604F9B',
    visible: true,
  },
  {
    id: 'line-dlr',
    name: 'DLR',
    stop: 'dlr',
    color: '#4FAFAF',
    visible: true,
  },
  {
    id: 'line-overground',
    name: 'Overground',
    stop: 'london-overground',
    color: '#E6873E',
    visible: true,
  },
  {
    id: 'line-tram',
    name: 'Tram',
    stop: 'tram-tram',
    color: '#8AC056',
    visible: true,
  },
  {
    id: 'line-waterloo-and-city',
    name: 'Waterloo and City',
    stop: 'waterloo-city',
    color: '#96CCBD',
    visible: true,
  },
  {
    id: 'line-emirates-air-line',
    name: 'Emirates Air Line',
    stop: 'emirates-air-line',
    color: '#DB4433',
    visible: true,
  },
];
