import { Station } from '../../typings';
import { LondonLineId } from './lines';

export const LONDON_STATIONS: Station[] = [
  {
    id: 'station-bethnal-green',
    name: 'Bethnal Green',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-cambridge-heath',
    name: 'Cambridge Heath',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-london-fields',
    name: 'London Fields',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-rectory-road',
    name: 'Rectory Road',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-wood-street',
    name: 'Wood Street',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-bruce-grove',
    name: 'Bruce Grove',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-white-hart-lane',
    name: 'White Hart Lane',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-silver-street',
    name: 'Silver Street',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-southbury',
    name: 'Southbury',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-turkey-street',
    name: 'Turkey Street',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-theobalds-grove',
    name: 'Theobalds Grove',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-enfield-town',
    name: 'Enfield Town',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-stamford-hill',
    name: 'Stamford Hill',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-bush-hill-park',
    name: 'Bush Hill Park',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-highams-park',
    name: 'Highams Park',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-chingford',
    name: 'Chingford',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-clapton',
    name: 'Clapton',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-st-james-street',
    name: 'St James Street',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-stoke-newington',
    name: 'Stoke Newington',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-hackney-downs',
    name: 'Hackney Downs',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-edmonton-green',
    name: 'Edmonton Green',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-cheshunt',
    name: 'Cheshunt',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-ilford',
    name: 'Ilford',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-goodmayes',
    name: 'Goodmayes',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-chadwell-heath',
    name: 'Chadwell Heath',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-romford',
    name: 'Romford',
    visible: false,
    lines: [LondonLineId.ELIZABETH, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-gidea-park',
    name: 'Gidea Park',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-harold-wood',
    name: 'Harold Wood',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-shenfield',
    name: 'Shenfield',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-brentwood',
    name: 'Brentwood',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-seven-kings',
    name: 'Seven Kings',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-emerson-park',
    name: 'Emerson Park',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-maryland',
    name: 'Maryland',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-manor-park',
    name: 'Manor Park',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-forest-gate',
    name: 'Forest Gate',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-chorleywood',
    name: 'Chorleywood',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-rickmansworth',
    name: 'Rickmansworth',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-chesham',
    name: 'Chesham',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-amersham',
    name: 'Amersham',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-chalfont-and-latimer',
    name: 'Chalfont and Latimer',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-moor-park',
    name: 'Moor Park',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-watford',
    name: 'Watford',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-croxley',
    name: 'Croxley',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-northwood',
    name: 'Northwood',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-northwood-hills',
    name: 'Northwood Hills',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-pinner',
    name: 'Pinner',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-north-harrow',
    name: 'North Harrow',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-northwick-park',
    name: 'Northwick Park',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-west-harrow',
    name: 'West Harrow',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-ickenham',
    name: 'Ickenham',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-uxbridge',
    name: 'Uxbridge',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-hillingdon',
    name: 'Hillingdon',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-ruislip',
    name: 'Ruislip',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-ruislip-manor',
    name: 'Ruislip Manor',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-eastcote',
    name: 'Eastcote',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-harrow--on-the-hill',
    name: 'Harrow on the Hill',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-preston-road',
    name: 'Preston Road',
    visible: false,
    lines: [LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-wembley-park',
    name: 'Wembley Park',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.JUBILEE],
  },
  {
    id: 'station-stanmore',
    name: 'Stanmore',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-canons-park',
    name: 'Canons Park',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-queensbury',
    name: 'Queensbury',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-kingsbury',
    name: 'Kingsbury',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-neasden',
    name: 'Neasden',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-dollis-hill',
    name: 'Dollis Hill',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-willesden-green',
    name: 'Willesden Green',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-kilburn',
    name: 'Kilburn',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-baker-street',
    name: 'Baker Street',
    visible: false,
    lines: [
      LondonLineId.JUBILEE,
      LondonLineId.BAKERLOO,
      LondonLineId.CIRCLE,
      LondonLineId.METROPOLITAN,
      LondonLineId.HAMMERSMITH_AND_CITY,
    ],
  },
  {
    id: 'station-aldgate',
    name: 'Aldgate',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.CIRCLE],
  },
  {
    id: 'station-barbican',
    name: 'Barbican',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.CIRCLE, LondonLineId.HAMMERSMITH_AND_CITY],
  },
  {
    id: 'station-great-portland-street',
    name: 'Great Portland Street',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.CIRCLE, LondonLineId.HAMMERSMITH_AND_CITY],
  },
  {
    id: 'station-farringdon',
    name: 'Farringdon',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.CIRCLE, LondonLineId.HAMMERSMITH_AND_CITY],
  },
  {
    id: 'station-liverpool-street',
    name: 'Liverpool Street',
    visible: false,
    lines: [
      LondonLineId.METROPOLITAN,
      LondonLineId.CIRCLE,
      LondonLineId.HAMMERSMITH_AND_CITY,
      LondonLineId.CENTRAL,
      LondonLineId.ELIZABETH,
    ],
  },
  {
    id: 'station-moorgate',
    name: 'Moorgate',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.CIRCLE, LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.NORTHERN],
  },
  {
    id: 'station-kings-cross-and-st-pancras-international',
    name: 'King’s Cross and St Pancras International',
    visible: false,
    lines: [
      LondonLineId.METROPOLITAN,
      LondonLineId.CIRCLE,
      LondonLineId.HAMMERSMITH_AND_CITY,
      LondonLineId.NORTHERN,
      LondonLineId.PICCADILLY,
      LondonLineId.VICTORIA,
    ],
  },
  {
    id: 'station-euston-square',
    name: 'Euston Square',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.CIRCLE, LondonLineId.HAMMERSMITH_AND_CITY],
  },
  {
    id: 'station-mansion-house',
    name: 'Mansion House',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT],
  },
  {
    id: 'station-monument',
    name: 'Monument',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT],
  },
  {
    id: 'station-south-kensington',
    name: 'South Kensington',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-sloane-square',
    name: 'Sloane Square',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT],
  },
  {
    id: 'station-cannon-street',
    name: 'Cannon Street',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT],
  },
  {
    id: 'station-westminster',
    name: 'Westminster',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT, LondonLineId.JUBILEE],
  },
  {
    id: 'station-gloucester-road',
    name: 'Gloucester Road',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-st-james-park',
    name: 'St James’s Park',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT],
  },
  {
    id: 'station-temple',
    name: 'Temple',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT],
  },
  {
    id: 'station-embankment',
    name: 'Embankment',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT, LondonLineId.NORTHERN, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-blackfriars',
    name: 'Blackfriars',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT],
  },
  {
    id: 'station-bayswater',
    name: 'Bayswater',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT],
  },
  {
    id: 'station-high-street-kensington',
    name: 'High Street Kensington',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT],
  },
  {
    id: 'station-notting-hill-gate',
    name: 'Notting Hill Gate',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT, LondonLineId.CENTRAL],
  },
  {
    id: 'station-paddington',
    name: 'Paddington',
    visible: false,
    lines: [
      LondonLineId.ELIZABETH,
      LondonLineId.CIRCLE,
      LondonLineId.DISTRICT,
      LondonLineId.BAKERLOO,
      LondonLineId.HAMMERSMITH_AND_CITY,
    ],
  },
  {
    id: 'station-edgware-road',
    name: 'Edgware Road',
    visible: false,
    lines: [LondonLineId.CIRCLE, LondonLineId.DISTRICT, LondonLineId.BAKERLOO, LondonLineId.HAMMERSMITH_AND_CITY],
  },
  {
    id: 'station-watford-high-street',
    name: 'Watford High Street',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-carpenders-park',
    name: 'Carpenders Park',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-hatch-end',
    name: 'Hatch End',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-kenton',
    name: 'Kenton',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-headstone-lane',
    name: 'Headstone Lane',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-harrow-and-wealdstone',
    name: 'Harrow and Wealdstone',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-bushey',
    name: 'Bushey',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-watford-junction',
    name: 'Watford Junction',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-north-wembley',
    name: 'North Wembley',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-south-kenton',
    name: 'South Kenton',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-kensal-green',
    name: 'Kensal Green',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-queens-park',
    name: 'Queen’s Park',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-stonebridge-park',
    name: 'Stonebridge Park',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-harlesden',
    name: 'Harlesden',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-willesden-junction',
    name: 'Willesden Junction',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-wembley-central',
    name: 'Wembley Central',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.BAKERLOO],
  },
  {
    id: 'station-kilburn-park',
    name: 'Kilburn Park',
    visible: false,
    lines: [LondonLineId.BAKERLOO],
  },
  {
    id: 'station-marylebone',
    name: 'Marylebone',
    visible: false,
    lines: [LondonLineId.BAKERLOO],
  },
  {
    id: 'station-warwick-avenue',
    name: 'Warwick Avenue',
    visible: false,
    lines: [LondonLineId.BAKERLOO],
  },
  {
    id: 'station-maida-vale',
    name: 'Maida Vale',
    visible: false,
    lines: [LondonLineId.BAKERLOO],
  },
  {
    id: 'station-elephant-and-castle',
    name: 'Elephant and Castle',
    visible: false,
    lines: [LondonLineId.BAKERLOO, LondonLineId.NORTHERN],
  },
  {
    id: 'station-regents-park',
    name: 'Regent’s Park',
    visible: false,
    lines: [LondonLineId.BAKERLOO],
  },
  {
    id: 'station-oxford-circus',
    name: 'Oxford Circus',
    visible: false,
    lines: [LondonLineId.BAKERLOO, LondonLineId.CENTRAL, LondonLineId.VICTORIA],
  },
  {
    id: 'station-piccadilly-circus',
    name: 'Piccadilly Circus',
    visible: false,
    lines: [LondonLineId.BAKERLOO, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-charing-cross',
    name: 'Charing Cross',
    visible: false,
    lines: [LondonLineId.BAKERLOO, LondonLineId.NORTHERN],
  },
  {
    id: 'station-euston',
    name: 'Euston',
    visible: false,
    lines: [LondonLineId.NORTHERN, LondonLineId.VICTORIA, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-perivale',
    name: 'Perivale',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-hanger-lane',
    name: 'Hanger Lane',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-ruislip-gardens',
    name: 'Ruislip Gardens',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-south-ruislip',
    name: 'South Ruislip',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-greenford',
    name: 'Greenford',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-northolt',
    name: 'Northolt',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-west-ruislip',
    name: 'West Ruislip',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-ealing-broadway',
    name: 'Ealing Broadway',
    visible: false,
    lines: [LondonLineId.ELIZABETH, LondonLineId.CENTRAL, LondonLineId.DISTRICT],
  },
  {
    id: 'station-west-acton',
    name: 'West Acton',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-bond-street',
    name: 'Bond Street',
    visible: false,
    lines: [LondonLineId.ELIZABETH, LondonLineId.CENTRAL, LondonLineId.JUBILEE],
  },
  {
    id: 'station-north-acton',
    name: 'North Acton',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-queensway',
    name: 'Queensway',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-marble-arch',
    name: 'Marble Arch',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-east-acton',
    name: 'East Acton',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-white-city',
    name: 'White City',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-shepherds-bush',
    name: 'Shepherd’s Bush',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-tottenham-court-road',
    name: 'Tottenham Court Road',
    visible: false,
    lines: [LondonLineId.ELIZABETH, LondonLineId.CENTRAL, LondonLineId.NORTHERN],
  },
  {
    id: 'station-mile-end',
    name: 'Mile End',
    visible: false,
    lines: [LondonLineId.CENTRAL, LondonLineId.DISTRICT, LondonLineId.HAMMERSMITH_AND_CITY],
  },
  {
    id: 'station-holborn',
    name: 'Holborn',
    visible: false,
    lines: [LondonLineId.CENTRAL, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-st-pauls',
    name: 'St Paul’s',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-bank',
    name: 'Bank',
    visible: false,
    lines: [LondonLineId.CENTRAL, LondonLineId.NORTHERN, LondonLineId.WATERLOO],
  },
  {
    id: 'station-chancery-lane',
    name: 'Chancery Lane',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-leytonstone',
    name: 'Leytonstone',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-leyton',
    name: 'Leyton',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-redbridge',
    name: 'Redbridge',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-gants-hill',
    name: 'Gants Hill',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-wanstead',
    name: 'Wanstead',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-stratford',
    name: 'Stratford',
    visible: false,
    lines: [LondonLineId.CENTRAL, LondonLineId.JUBILEE, LondonLineId.DLR, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-woodford',
    name: 'Woodford',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-south-woodford',
    name: 'South Woodford',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-snaresbrook',
    name: 'Snaresbrook',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-hainault',
    name: 'Hainault',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-fairlop',
    name: 'Fairlop',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-barkingside',
    name: 'Barkingside',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-newbury-park',
    name: 'Newbury Park',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-roding-valley',
    name: 'Roding Valley',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-grange-hill',
    name: 'Grange Hill',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-chigwell',
    name: 'Chigwell',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-theydon-bois',
    name: 'Theydon Bois',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-epping',
    name: 'Epping',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-debden',
    name: 'Debden',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-loughton',
    name: 'Loughton',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-buckhurst-hill',
    name: 'Buckhurst Hill',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-shepherds-bush-market',
    name: 'Shepherd’s Bush Market',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.CIRCLE],
  },
  {
    id: 'station-goldhawk-road',
    name: 'Goldhawk Road',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.CIRCLE],
  },
  {
    id: 'station-latimer-road',
    name: 'Latimer Road',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.CIRCLE],
  },
  {
    id: 'station-ladbroke-grove',
    name: 'Ladbroke Grove',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.CIRCLE],
  },
  {
    id: 'station-royal-oak',
    name: 'Royal Oak',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.CIRCLE],
  },
  {
    id: 'station-westbourne-park',
    name: 'Westbourne Park',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.CIRCLE],
  },
  {
    id: 'station-wood-lane',
    name: 'Wood Lane',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.CIRCLE],
  },
  {
    id: 'station-hammersmith',
    name: 'Hammersmith',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.CIRCLE, LondonLineId.DISTRICT, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-bow-road',
    name: 'Bow Road',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.DISTRICT],
  },
  {
    id: 'station-west-ham',
    name: 'West Ham',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.DISTRICT, LondonLineId.JUBILEE],
  },
  {
    id: 'station-whitechapel',
    name: 'Whitechapel',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.DISTRICT, LondonLineId.OVERGROUND, LondonLineId.ELIZABETH],
  },
  {
    id: 'station-aldgate-east',
    name: 'Aldgate East',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.DISTRICT],
  },
  {
    id: 'station-stepney-green',
    name: 'Stepney Green',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.DISTRICT],
  },
  {
    id: 'station-bromley--by-bow',
    name: 'Bromley by Bow',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.DISTRICT],
  },
  {
    id: 'station-east-ham',
    name: 'East Ham',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.DISTRICT],
  },
  {
    id: 'station-plaistow',
    name: 'Plaistow',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.DISTRICT],
  },
  {
    id: 'station-upton-park',
    name: 'Upton Park',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.DISTRICT],
  },
  {
    id: 'station-barking',
    name: 'Barking',
    visible: false,
    lines: [LondonLineId.HAMMERSMITH_AND_CITY, LondonLineId.DISTRICT, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-barking-riverside',
    name: 'Barking Riverside',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-elm-park',
    name: 'Elm Park',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-dagenham-east',
    name: 'Dagenham East',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-dagenham-heathway',
    name: 'Dagenham Heathway',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-becontree',
    name: 'Becontree',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-upney',
    name: 'Upney',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-upminster-bridge',
    name: 'Upminster Bridge',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-hornchurch',
    name: 'Hornchurch',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-upminster',
    name: 'Upminster',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-fulham-broadway',
    name: 'Fulham Broadway',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-parsons-green',
    name: 'Parsons Green',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-east-putney',
    name: 'East Putney',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-southfields',
    name: 'Southfields',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-wimbledon-park',
    name: 'Wimbledon Park',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-west-brompton',
    name: 'West Brompton',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-wimbledon',
    name: 'Wimbledon',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.TRAM],
  },
  {
    id: 'station-earls-court',
    name: 'Earl’s Court',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-chiswick-park',
    name: 'Chiswick Park',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-turnham-green',
    name: 'Turnham Green',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-stamford-brook',
    name: 'Stamford Brook',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-ravenscourt-park',
    name: 'Ravenscourt Park',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-west-kensington',
    name: 'West Kensington',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-barons-court',
    name: 'Barons Court',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-ealing-common',
    name: 'Ealing Common',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-gunnersbury',
    name: 'Gunnersbury',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-kew-gardens',
    name: 'Kew Gardens',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-richmond',
    name: 'Richmond',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-royal-docks',
    name: 'Royal Docks',
    visible: false,
    lines: [LondonLineId.EMIRATES_AIR_LINE],
  },
  {
    id: 'station-greenwich-peninsula',
    name: 'Greenwich Peninsula',
    visible: false,
    lines: [LondonLineId.EMIRATES_AIR_LINE],
  },
  {
    id: 'station-canada-water',
    name: 'Canada Water',
    visible: false,
    lines: [LondonLineId.JUBILEE, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-green-park',
    name: 'Green Park',
    visible: false,
    lines: [LondonLineId.JUBILEE, LondonLineId.PICCADILLY, LondonLineId.VICTORIA],
  },
  {
    id: 'station-london-bridge',
    name: 'London Bridge',
    visible: false,
    lines: [LondonLineId.JUBILEE, LondonLineId.NORTHERN],
  },
  {
    id: 'station-bermondsey',
    name: 'Bermondsey',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-southwark',
    name: 'Southwark',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-waterloo',
    name: 'Waterloo',
    visible: false,
    lines: [LondonLineId.JUBILEE, LondonLineId.NORTHERN, LondonLineId.BAKERLOO, LondonLineId.WATERLOO],
  },
  {
    id: 'station-north-greenwich',
    name: 'North Greenwich',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-mill-hill-east',
    name: 'Mill Hill East',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-high-barnet',
    name: 'High Barnet',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-totteridge-and-whetstone',
    name: 'Totteridge and Whetstone',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-woodside-park',
    name: 'Woodside Park',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-west-finchley',
    name: 'West Finchley',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-finchley-central',
    name: 'Finchley Central',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-east-finchley',
    name: 'East Finchley',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-highgate',
    name: 'Highgate',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-archway',
    name: 'Archway',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-kentish-town',
    name: 'Kentish Town',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-tufnell-park',
    name: 'Tufnell Park',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-edgware',
    name: 'Edgware',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-burnt-oak',
    name: 'Burnt Oak',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-colindale',
    name: 'Colindale',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-hendon-central',
    name: 'Hendon Central',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-brent-cross',
    name: 'Brent Cross',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-golders-green',
    name: 'Golders Green',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-hampstead',
    name: 'Hampstead',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-belsize-park',
    name: 'Belsize Park',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-chalk-farm',
    name: 'Chalk Farm',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-camden-town',
    name: 'Camden Town',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-mornington-crescent',
    name: 'Mornington Crescent',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-goodge-street',
    name: 'Goodge Street',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-warren-street',
    name: 'Warren Street',
    visible: false,
    lines: [LondonLineId.NORTHERN, LondonLineId.VICTORIA],
  },
  {
    id: 'station-leicester-square',
    name: 'Leicester Square',
    visible: false,
    lines: [LondonLineId.NORTHERN, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-borough',
    name: 'Borough',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-angel',
    name: 'Angel',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-nine-elms',
    name: 'Nine Elms',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-battersea-power-station',
    name: 'Battersea Power Station',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-old-street',
    name: 'Old Street',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-kennington',
    name: 'Kennington',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-clapham-north',
    name: 'Clapham North',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-clapham-high-street',
    name: 'Clapham High Street',
    visible: false,
    lines: [LondonLineId.NORTHERN, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-oval',
    name: 'Oval',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-clapham-common',
    name: 'Clapham Common',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-clapham-south',
    name: 'Clapham South',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-tooting-bec',
    name: 'Tooting Bec',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-tooting-broadway',
    name: 'Tooting Broadway',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-colliers-wood',
    name: 'Colliers Wood',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-south-wimbledon',
    name: 'South Wimbledon',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-morden',
    name: 'Morden',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-balham',
    name: 'Balham',
    visible: false,
    lines: [LondonLineId.NORTHERN],
  },
  {
    id: 'station-rayners-lane',
    name: 'Rayners Lane',
    visible: false,
    lines: [LondonLineId.METROPOLITAN, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-south-harrow',
    name: 'South Harrow',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-sudbury-hill',
    name: 'Sudbury Hill',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-sudbury-town',
    name: 'Sudbury Town',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-alperton',
    name: 'Alperton',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-park-royal',
    name: 'Park Royal',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-north-ealing',
    name: 'North Ealing',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-heathrow-terminal-4',
    name: 'Heathrow Terminal 4',
    visible: false,
    lines: [LondonLineId.ELIZABETH, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-heathrow-terminal-5',
    name: 'Heathrow Terminal 5',
    visible: false,
    lines: [LondonLineId.ELIZABETH, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-northfields',
    name: 'Northfields',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-boston-manor',
    name: 'Boston Manor',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-south-ealing',
    name: 'South Ealing',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-osterley',
    name: 'Osterley',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-hounslow-central',
    name: 'Hounslow Central',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-hounslow-east',
    name: 'Hounslow East',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-hounslow-west',
    name: 'Hounslow West',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-hatton-cross',
    name: 'Hatton Cross',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-heathrow-terminals-2-and-3',
    name: 'Heathrow Terminals 2 and 3',
    visible: false,
    lines: [LondonLineId.ELIZABETH, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-russell-square',
    name: 'Russell Square',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-hyde-park-corner',
    name: 'Hyde Park Corner',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-knightsbridge',
    name: 'Knightsbridge',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-covent-garden',
    name: 'Covent Garden',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-oakwood',
    name: 'Oakwood',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-cockfosters',
    name: 'Cockfosters',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-southgate',
    name: 'Southgate',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-arnos-grove',
    name: 'Arnos Grove',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-bounds-green',
    name: 'Bounds Green',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-wood-green',
    name: 'Wood Green',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-turnpike-lane',
    name: 'Turnpike Lane',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-manor-house',
    name: 'Manor House',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-arsenal',
    name: 'Arsenal',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-holloway-road',
    name: 'Holloway Road',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-blackhorse-road',
    name: 'Blackhorse Road',
    visible: false,
    lines: [LondonLineId.VICTORIA, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-highbury-and-islington',
    name: 'Highbury and Islington',
    visible: false,
    lines: [LondonLineId.VICTORIA, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-finsbury-park',
    name: 'Finsbury Park',
    visible: false,
    lines: [LondonLineId.VICTORIA, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-seven-sisters',
    name: 'Seven Sisters',
    visible: false,
    lines: [LondonLineId.VICTORIA, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-tottenham-hale',
    name: 'Tottenham Hale',
    visible: false,
    lines: [LondonLineId.VICTORIA],
  },
  {
    id: 'station-walthamstow-central',
    name: 'Walthamstow Central',
    visible: false,
    lines: [LondonLineId.VICTORIA, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-pimlico',
    name: 'Pimlico',
    visible: false,
    lines: [LondonLineId.VICTORIA],
  },
  {
    id: 'station-vauxhall',
    name: 'Vauxhall',
    visible: false,
    lines: [LondonLineId.VICTORIA],
  },
  {
    id: 'station-stockwell',
    name: 'Stockwell',
    visible: false,
    lines: [LondonLineId.VICTORIA, LondonLineId.NORTHERN],
  },
  {
    id: 'station-brixton',
    name: 'Brixton',
    visible: false,
    lines: [LondonLineId.VICTORIA],
  },
  {
    id: 'station-west-silvertown',
    name: 'West Silvertown',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-pontoon-dock',
    name: 'Pontoon Dock',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-king-george-v',
    name: 'King George V',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-prince-regent',
    name: 'Prince Regent',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-royal-albert',
    name: 'Royal Albert',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-beckton-park',
    name: 'Beckton Park',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-cyprus',
    name: 'Cyprus',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-gallions-reach',
    name: 'Gallions Reach',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-beckton',
    name: 'Beckton',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-blackwall',
    name: 'Blackwall',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-royal-victoria',
    name: 'Royal Victoria',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-bow-church',
    name: 'Bow Church',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-island-gardens',
    name: 'Island Gardens',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-deptford-bridge',
    name: 'Deptford Bridge',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-south-quay',
    name: 'South Quay',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-crossharbour',
    name: 'Crossharbour',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-mudchute',
    name: 'Mudchute',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-heron-quays',
    name: 'Heron Quays',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-west-india-quay',
    name: 'West India Quay',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-elverson-road',
    name: 'Elverson Road',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-devons-road',
    name: 'Devons Road',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-langdon-park',
    name: 'Langdon Park',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-all-saints',
    name: 'All Saints',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-canning-town',
    name: 'Canning Town',
    visible: false,
    lines: [LondonLineId.DLR, LondonLineId.JUBILEE],
  },
  {
    id: 'station-poplar',
    name: 'Poplar',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-pudding-mill-lane',
    name: 'Pudding Mill Lane',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-east-india',
    name: 'East India',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-london-city-airport',
    name: 'London City Airport',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-limehouse',
    name: 'Limehouse',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-woolwich-arsenal',
    name: 'Woolwich Arsenal',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-woolwich',
    name: 'Woolwich',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-abbey-wood',
    name: 'Abbey Wood',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-cutty-sark',
    name: 'Cutty Sark',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-greenwich',
    name: 'Greenwich',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-lewisham',
    name: 'Lewisham',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-tower-gateway',
    name: 'Tower Gateway',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-stratford-international',
    name: 'Stratford International',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-tower-hill',
    name: 'Tower Hill',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-fenchurch-st',
    name: 'Fenchurch St',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-stratford-high-street',
    name: 'Stratford High Street',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-abbey-road',
    name: 'Abbey Road',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-star-lane',
    name: 'Star Lane',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-acton-central',
    name: 'Acton Central',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-south-acton',
    name: 'South Acton',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-kensington-olympia',
    name: 'Kensington (Olympia)',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.DISTRICT],
  },
  {
    id: 'station-kilburn-high-road',
    name: 'Kilburn High Road',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-south-hampstead',
    name: 'South Hampstead',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-kensal-rise',
    name: 'Kensal Rise',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-brondesbury-park',
    name: 'Brondesbury Park',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-hampstead-heath',
    name: 'Hampstead Heath',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-finchley-road-and-frognal',
    name: 'Finchley Road and Frognal',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-brondesbury',
    name: 'Brondesbury',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-gospel-oak',
    name: 'Gospel Oak',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-kentish-town-west',
    name: 'Kentish Town West',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-camden-road',
    name: 'Camden Road',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-dalston-kingsland',
    name: 'Dalston Kingsland',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-hackney-central',
    name: 'Hackney Central',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-caledonian-road-and-barnsbury',
    name: 'Caledonian Road and Barnsbury',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-hackney-wick',
    name: 'Hackney Wick',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-homerton',
    name: 'Homerton',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-canonbury',
    name: 'Canonbury',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-norwood-junction',
    name: 'Norwood Junction',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-forest-hill',
    name: 'Forest Hill',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-anerley',
    name: 'Anerley',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-penge-west',
    name: 'Penge West',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-honor-oak-park',
    name: 'Honor Oak Park',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-brockley',
    name: 'Brockley',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-west-croydon',
    name: 'West Croydon',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-wapping',
    name: 'Wapping',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-new-cross-gate',
    name: 'New Cross Gate',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-sydenham',
    name: 'Sydenham',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-new-cross',
    name: 'New Cross',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-crystal-palace',
    name: 'Crystal Palace',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-surrey-quays',
    name: 'Surrey Quays',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-rotherhithe',
    name: 'Rotherhithe',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-shadwell',
    name: 'Shadwell',
    visible: false,
    lines: [LondonLineId.OVERGROUND, LondonLineId.DLR],
  },
  {
    id: 'station-queens-road-peckham',
    name: 'Queens Road Peckham',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-peckham-rye',
    name: 'Peckham Rye',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-denmark-hill',
    name: 'Denmark Hill',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-wandsworth-road',
    name: 'Wandsworth Road',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-imperial-wharf',
    name: 'Imperial Wharf',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-wanstead-park',
    name: 'Wanstead Park',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-leytonstone-high-road',
    name: 'Leytonstone High Road',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-leyton-midland-road',
    name: 'Leyton Midland Road',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-walthamstow-queens-road',
    name: 'Walthamstow Queen’s Road',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-woodgrange-park',
    name: 'Woodgrange Park',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-acton-town',
    name: 'Acton Town',
    visible: false,
    lines: [LondonLineId.DISTRICT, LondonLineId.PICCADILLY],
  },
  {
    id: 'station-harringay-green-lanes',
    name: 'Harringay Green Lanes',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-south-tottenham',
    name: 'South Tottenham',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-upper-holloway',
    name: 'Upper Holloway',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-crouch-hill',
    name: 'Crouch Hill',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-shoreditch-high-street',
    name: 'Shoreditch High Street',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-dalston-junction',
    name: 'Dalston Junction',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-haggerston',
    name: 'Haggerston',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-hoxton',
    name: 'Hoxton',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-clapham-junction',
    name: 'Clapham Junction',
    visible: false,
    lines: [LondonLineId.OVERGROUND],
  },
  {
    id: 'station-holland-park',
    name: 'Holland Park',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-caledonian-road',
    name: 'Caledonian Road',
    visible: false,
    lines: [LondonLineId.PICCADILLY],
  },
  {
    id: 'station-victoria',
    name: 'Victoria',
    visible: false,
    lines: [LondonLineId.VICTORIA, LondonLineId.CIRCLE, LondonLineId.DISTRICT],
  },
  {
    id: 'station-harrington-road',
    name: 'Harrington Road',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-arena',
    name: 'Arena',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-dundonald-road',
    name: 'Dundonald Road',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-merton-park',
    name: 'Merton Park',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-woodside',
    name: 'Woodside',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-blackhorse-lane',
    name: 'Blackhorse Lane',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-addiscombe',
    name: 'Addiscombe',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-avenue-road',
    name: 'Avenue Road',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-sandilands',
    name: 'Sandilands',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-king-henrys-drive',
    name: 'King Henry’s Drive',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-new-addington',
    name: 'New Addington',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-fieldway',
    name: 'Fieldway',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-addington-village',
    name: 'Addington Village',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-gravel-hill',
    name: 'Gravel Hill',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-coombe-lane',
    name: 'Coombe Lane',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-lloyd-park',
    name: 'Lloyd Park',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-wellesley-road',
    name: 'Wellesley Road',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-reeves-corner',
    name: 'Reeves Corner',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-mitcham',
    name: 'Mitcham',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-beddington-lane',
    name: 'Beddington Lane',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-ampere-way',
    name: 'Ampere Way',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-wandle-park',
    name: 'Wandle Park',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-centrale',
    name: 'Centrale',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-church-street',
    name: 'Church Street',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-belgrave-walk',
    name: 'Belgrave Walk',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-phipps-bridge',
    name: 'Phipps Bridge',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-morden-road',
    name: 'Morden Road',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-therapia-lane',
    name: 'Therapia Lane',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-waddon-marsh',
    name: 'Waddon Marsh',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-george-street',
    name: 'George Street',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-lebanon-road',
    name: 'Lebanon Road',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-beckenham-road',
    name: 'Beckenham Road',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-mitcham-junction',
    name: 'Mitcham Junction',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-east-croydon',
    name: 'East Croydon',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-elmers-end',
    name: 'Elmers End',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-birkbeck',
    name: 'Birkbeck',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-beckenham-junction',
    name: 'Beckenham Junction',
    visible: false,
    lines: [LondonLineId.TRAM],
  },
  {
    id: 'station-swiss-cottage',
    name: 'Swiss Cottage',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-finchley-road',
    name: 'Finchley Road',
    visible: false,
    lines: [LondonLineId.JUBILEE, LondonLineId.METROPOLITAN],
  },
  {
    id: 'station-west-hampstead',
    name: 'West Hampstead',
    visible: false,
    lines: [LondonLineId.JUBILEE, LondonLineId.OVERGROUND],
  },
  {
    id: 'station-st-johns-wood',
    name: 'St John’s Wood',
    visible: false,
    lines: [LondonLineId.JUBILEE],
  },
  {
    id: 'station-lancaster-gate',
    name: 'Lancaster Gate',
    visible: false,
    lines: [LondonLineId.CENTRAL],
  },
  {
    id: 'station-lambeth-north',
    name: 'Lambeth North',
    visible: false,
    lines: [LondonLineId.BAKERLOO],
  },
  {
    id: 'station-custom-house',
    name: 'Custom House',
    visible: false,
    lines: [LondonLineId.DLR, LondonLineId.ELIZABETH],
  },
  {
    id: 'station-west-ealing',
    name: 'West Ealing',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-acton-main-line',
    name: 'Acton Main Line',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-southall',
    name: 'Southall',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-west-drayton',
    name: 'West Drayton',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-iver',
    name: 'Iver',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-langley',
    name: 'Langley',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-burnham',
    name: 'Burnham',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-taplow',
    name: 'Taplow',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-hanwell',
    name: 'Hanwell',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-hayes-and-harlington',
    name: 'Hayes and Harlington',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-putney-bridge',
    name: 'Putney Bridge',
    visible: false,
    lines: [LondonLineId.DISTRICT],
  },
  {
    id: 'station-canary-wharf',
    name: 'Canary Wharf',
    visible: false,
    lines: [LondonLineId.JUBILEE, LondonLineId.DLR],
  },
  {
    id: 'station-westferry',
    name: 'Westferry',
    visible: false,
    lines: [LondonLineId.DLR],
  },
  {
    id: 'station-reading',
    name: 'Reading',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-twyford',
    name: 'Twyford',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-maidenhead',
    name: 'Maidenhead',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
  {
    id: 'station-slough',
    name: 'Slough',
    visible: false,
    lines: [LondonLineId.ELIZABETH],
  },
];
